name: Android CI

on:
  push:
    paths:
      - 'android/app/**'
  pull_request:
    paths:
      - 'android/app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/.android-sdk
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('android/app/**') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      - name: Grant execute permission
        run: chmod +x android/app/gradlew
      - name: Run checks
        run: bash android/scripts/gradle.sh ./gradlew :app:lintDebug :app:testDebugUnitTest
