from xml.etree import ElementTree as ET

from app.main import _build_prosody_tag


def _simulate_stream(chunks: list[str], prosody: dict[str, str | float]):
    """Return list of SSML chunks generated by the streaming loop."""

    return [_build_prosody_tag(chunk, prosody) for chunk in chunks]


def test_streamed_ssml_valid_after_fix():
    """Each streamed chunk should be valid SSML on its own (has <speak> root)."""

    prosody_cfg = {"rate": "200%"}
    chunks = ["Hello ", "world"]

    for ssml_chunk in _simulate_stream(chunks, prosody_cfg):
        ET.fromstring(ssml_chunk)  # should not raise 